### ISSUE TITLE
older versions wont work for me either!

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs-builder#26]
```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install androidjs@2.0.1

> androidjs@2.0.1 postinstall /home/cool/Desktop/myfirstapp/hatef/node_modules/androidjs
> node ./bin/postinstall.js

package.json File Detected
npm WARN hatef@1.0.0 No repository field.

+ androidjs@2.0.1
added 2 packages from 1 contributor, removed 6 packages, updated 13 packages, moved 1 package and audited 127 packages in 1.994s
found 0 vulnerabilities


```

**Comment by szhatef** [comment]
```sh
cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install -g androidjs-builder@2.0.2
/home/cool/.nvm/versions/node/v8.16.1/bin/androidjs -> /home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/test.js
+ androidjs-builder@2.0.2
added 598 packages from 955 contributors in 73.504s
cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs g
`generate` command will be deprecate soon; use `init`
                     _           _     _        _  _____ 
     /\             | |         (_)   | |      | |/ ____|
    /  \   _ __   __| |_ __ ___  _  __| |      | | (___  
   / /\ \ | '_ \ / _` | '__/ _ \| |/ _` |  _   | |\___ \ 
  / ____ \| | | | (_| | | | (_) | | (_| | | |__| |____) |
 /_/    \_\_| |_|\__,_|_|  \___/|_|\__,_|  \____/|_____/ 
                                                         
                                                         
? Application name: 
cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install

> hatef@1.0.0 install /home/cool/Desktop/myfirstapp/hatef
> adb install ./dist/app.apk

sh: 1: adb: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hatef@1.0.0 install: `adb install ./dist/app.apk`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hatef@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by szhatef** [comment]
```sh
cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs b
webview: hatef
building
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
    at Request.<anonymous> (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/lib/native_app.js:125:27)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at reportState (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:83:21)
    at call (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:28:16)
    at Object.throttled [as reportState] (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:20:26)
    at onData (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:44:36)
    at emitOne (events.js:121:20)
    at IncomingMessage.emit (events.js:211:7)

```

**Comment by szhatef** [comment]
```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs b
webview: hatef
building
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
 downloading sdk [ ============ ] 54320848/54345243 90207/bps 99% 0.3s done
extracting: https://github.com/android-js/androidjs-sdk to: /home/cool/.androidjs/androidjs-sdk
 ✔ done
copying Assets
copying from /home/cool/Desktop/myfirstapp/hatef 
to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
[ '/home/cool/Desktop/myfirstapp/hatef/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/cool/.androidjs/androidjs-sdk/AndroidManifest.xml
{ manifest: 
   { '$': 
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission': 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.hatef
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/cool/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'hatef', '$': { name: 'app_name' } }
Building APK
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

```

**Comment by szhatef** [comment]
```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install androidjs@2.0.0

> androidjs@2.0.0 postinstall /home/cool/Desktop/myfirstapp/hatef/node_modules/androidjs
> node ./bin/postinstall.js

package.json File Detected
npm WARN hatef@1.0.0 No description
npm WARN hatef@1.0.0 No repository field.

+ androidjs@2.0.0
added 1 package from 1 contributor and audited 127 packages in 4.515s
found 0 vulnerabilities

```

**Comment by szhatef** [comment]
```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs b
webview: hatef
checking Core
downloading androidjs-sdk  { Error: /home/cool/.androidjs/cache/config.json: ENOENT: no such file or directory, open '/home/cool/.androidjs/cache/config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/jsonfile/index.js:64:22)
    at internetAvailable.then (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/lib/check_for_update.js:26:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cool/.androidjs/cache/config.json' }
failed to connect

```

**Comment by szhatef** [comment]
```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs b
webview: hatef
checking Core
using core /home/cool/.androidjs/androidjs-sdk
removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/cool/Desktop/myfirstapp/hatef 
to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
[ '/home/cool/Desktop/myfirstapp/hatef/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/cool/.androidjs/androidjs-sdk/AndroidManifest.xml
{ Error: /home/cool/.androidjs/cache/config.json: ENOENT: no such file or directory, open '/home/cool/.androidjs/cache/config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.readFileSync (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/node_modules/jsonfile/index.js:64:22)
    at internetAvailable.then (/home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/lib/check_for_update.js:26:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cool/.androidjs/cache/config.json' }
failed to connect
{ manifest: 
   { '$': 
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission': 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.hatef
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/cool/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'hatef', '$': { name: 'app_name' } }
Building APK
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
cool@zenbook:~/Desktop/myfirstapp/hatef$ 

```

**Comment by szhatef** [comment]
Before installing each version I did delete any folder with androidjs* name.

I just need to rebuild an apk file, and no method helped me till now.

**Comment by szhatef** [comment]
```sh
cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install androidjs@2.0.1

> androidjs@2.0.1 postinstall /home/cool/Desktop/myfirstapp/hatef/node_modules/androidjs
> node ./bin/postinstall.js

package.json File Detected
npm WARN hatef@1.0.0 No description
npm WARN hatef@1.0.0 No repository field.

+ androidjs@2.0.1
added 1 package from 1 contributor and audited 127 packages in 2.645s
found 0 vulnerabilities

cool@zenbook:~/Desktop/myfirstapp/hatef$ npm install -g androidjs-builder@2.0.2
/home/cool/.nvm/versions/node/v8.16.1/bin/androidjs -> /home/cool/.nvm/versions/node/v8.16.1/lib/node_modules/androidjs-builder/test.js
+ androidjs-builder@2.0.2
added 598 packages from 955 contributors in 45.115s

```

**Comment by szhatef** [comment]
cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs b
webview: hatef
building
checking Core
using core /home/cool/.androidjs/androidjs-sdk
removing /home/cool/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/cool/Desktop/myfirstapp/hatef 
to: /home/cool/.androidjs/androidjs-sdk/assets/myapp
[ '/home/cool/Desktop/myfirstapp/hatef/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/cool/.androidjs/androidjs-sdk/AndroidManifest.xml
{ manifest: 
   { '$': 
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission': 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.hatef
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/cool/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'hatef', '$': { name: 'app_name' } }
Building APK
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
cool@zenbook:~/Desktop/myfirstapp/hatef$

**Comment by szhatef** [comment]
and something odd to me:
after removing all file and folders again:

```sh

cool@zenbook:~/Desktop/myfirstapp/hatef$ sudo npm install androidjs
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> androidjs@2.0.1 postinstall /home/cool/Desktop/myfirstapp/hatef/node_modules/androidjs
> node ./bin/postinstall.js

package.json File Detected
npm WARN hatef@1.0.0 No description
npm WARN hatef@1.0.0 No repository field.

+ androidjs@2.0.1
updated 1 package in 1.976s
cool@zenbook:~/Desktop/myfirstapp/hatef$ sudo androidjs -V
sudo: androidjs: command not found
cool@zenbook:~/Desktop/myfirstapp/hatef$ androidjs -V
bash: /home/cool/.nvm/versions/node/v8.16.1/bin/androidjs: No such file or directory
```

**Comment by Chhekur** [comment]
Do you have java installed in your computer > 1.8

**Comment by szhatef** [comment]
Problem solved :) I had NOT java JDK on my system, 
right now everything works fine :)
just installed it by : apt-get install default-jdk
and use new package.json compatible with this new version :)

Thanks alot :)
