### ISSUE TITLE
error while running androidjs init

### ISSUE THREAD

**Issue by anandayyappan** [android-js/androidjs-builder#28]
I am getting the following error while running androidjs init

i am using win10 with command prompt as admin

example downloaded
fs.js:127
    throw err;
    ^

Error: EPERM: operation not permitted, rename 'C:\ajsapp\vue-js-example' -> 'C:\ajsapp\appnew'
    at Object.renameSync (fs.js:651:3)
    at C:\Users\Krishna\AppData\Roaming\npm\node_modules\androidjs-builder\lib\native_app.js:45:20
    at Request._callback (C:\Users\Krishna\AppData\Roaming\npm\node_modules\androidjs-builder\lib\copy.js:115:44)
    at Request.self.callback (C:\Users\Krishna\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.<anonymous> (C:\Users\Krishna\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:214:15)
    at IncomingMessage.<anonymous> (C:\Users\Krishna\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:297:20)
    at IncomingMessage.emit (events.js:214:15) {
  errno: -4048,
  syscall: 'rename',
  code: 'EPERM',
  path: 'C:\\ajsapp\\vue-js-example',
  dest: 'C:\\ajsapp\\appnew'
}

**Comment by Chhekur** [comment]
Don't worry sometime this error occurs in windows, just change rename the folder by yourself ; )
