### ISSUE TITLE
Error on building the apk

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs-builder#30]
Hello! Launching androidjs b -f it returns this error:
```
Building APK
I: Using Apktool 2.4.0

I: Checking whether sources has changed...

I: Smaling smali folder into classes.dex...

I: Checking whether resources has changed...

I: Building resources...

ERROR: failed to build .apk
stderr: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741701): [C:\Users\Mattia\AppData\Local\Temp\brut_util_Jar_1370595960298177441.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 28, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\Mattia\AppData\Local\Temp\APKTOOL3662210172369573480.tmp, -0, resources.arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_livedata.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.legacy_legacy-support-v4.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.media_media.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, png, -0, assets/myapp/node_modules/axios/index.js, -0, assets/myapp/node_modules/better-assert/Makefile, -0, assets/myapp/node_modules/callsite/Makefile, -0, assets/myapp/node_modules/engine.io-client/node_modules/debug/node.js, -0, assets/myapp/node_modules/engine.io/node_modules/debug/node.js, -0, assets/myapp/node_modules/follow-redirects/http.js, -0, assets/myapp/node_modules/follow-redirects/https.js, -0, assets/myapp/node_modules/follow-redirects/node_modules/debug/node.js, -0, assets/myapp/node_modules/localtunnel/node_modules/debug/node.js, -0, assets/myapp/node_modules/parseqs/Makefile, -0, assets/myapp/node_modules/parseuri/Makefile, -0, assets/myapp/node_modules/resolve/test/dotdot/index.js, -0, assets/myapp/node_modules/resolve/test/dotdot/abc/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/xmodules/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/ymodules/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/zmodules/bbb/main.js, -0, assets/myapp/node_modules/resolve/test/node_path/x/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/x/ccc/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/y/bbb/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/y/ccc/index.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa.js, -0, assets/myapp/node_modules/resolve/test/precedence/bbb.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa/main.js, -0, assets/myapp/node_modules/resolve/test/precedence/bbb/main.js, -0, assets/myapp/node_modules/resolve/test/resolver/cup.coffee, -0, assets/myapp/node_modules/resolve/test/resolver/foo.js, -0, assets/myapp/node_modules/resolve/test/resolver/baz/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/baz/quux.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_main/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/dot_slash_main/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_slash_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/incorrect_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/quux/foo/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/same_names/foo.js, -0, assets/myapp/node_modules/resolve/test/resolver/same_names/foo/index.js, -0, assets/myapp/node_modules/socket.io-client/node_modules/debug/node.js, -0, assets/myapp/node_modules/socket.io-parser/node_modules/debug/node.js, -0, assets/myapp/node_modules/xmlhttprequest-ssl/tests/testdata.txt, -0, arsc, -I, C:\Users\Mattia\.androidjs\cache\1.apk, -S, C:\Users\Mattia\.androidjs\androidjs-sdk\res, -M, C:\Users\Mattia\.androidjs\androidjs-sdk\AndroidManifest.xml]

build process exited with code 1
```

**Comment by Chhekur** [comment]
why did you renamed all the folders ?

**Comment by Romans96** [comment]
> why did you renamed all the folders ?

For all i meant, the main folder, that rest vue-example, and in the package the app-name and the name that rest vue example too, but also after that it retrives that error too

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )

**Comment by llaakso** [comment]
I tried to create sample project but got similar result:

```
> androidjs b -f
Downloading: https://github.com/android-js/androidjs-sdk/archive/master.zip
copying assets ...
updating app name...
Setting app version ...
Version Code: 1
Version Name: 1.0
updating theme ...
theme attribute not found in package.json
Using SDK: 2.0.8
Building Apk ...
non zero exit code: failed to build apk
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\backs\AppData\Local\Temp\brut_util_Jar_5935785716025185795.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 28, --version-code, 1000032, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\backs\AppData\Local\Temp\APKTOOL6398129246983956937.tmp, -0, resources.arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_livedata.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.legacy_legacy-support-v4.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.media_media.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, png, -0, assets/myapp/node_modules/axios/index.js, -0, assets/myapp/node_modules/better-assert/Makefile, -0, assets/myapp/node_modules/callsite/Makefile, -0, assets/myapp/node_modules/engine.io-client/node_modules/debug/node.js, -0, assets/myapp/node_modules/engine.io/node_modules/debug/node.js, -0, assets/myapp/node_modules/follow-redirects/http.js, -0, assets/myapp/node_modules/follow-redirects/https.js, -0, assets/myapp/node_modules/follow-redirects/node_modules/debug/node.js, -0, assets/myapp/node_modules/localtunnel/node_modules/debug/node.js, -0, assets/myapp/node_modules/parseqs/Makefile, -0, assets/myapp/node_modules/parseuri/Makefile, -0, assets/myapp/node_modules/readable-stream/duplex-browser.js, -0, assets/myapp/node_modules/readable-stream/duplex.js, -0, assets/myapp/node_modules/readable-stream/passthrough.js, -0, assets/myapp/node_modules/readable-stream/transform.js, -0, assets/myapp/node_modules/readable-stream/writable-browser.js, -0, assets/myapp/node_modules/readable-stream/lib/internal/streams/stream.js, -0, assets/myapp/node_modules/resolve/test/dotdot/index.js, -0, assets/myapp/node_modules/resolve/test/dotdot/abc/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/xmodules/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/ymodules/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/module_dir/zmodules/bbb/main.js, -0, assets/myapp/node_modules/resolve/test/node_path/x/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/x/ccc/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/y/bbb/index.js, -0, assets/myapp/node_modules/resolve/test/node_path/y/ccc/index.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa.js, -0, assets/myapp/node_modules/resolve/test/precedence/bbb.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa/index.js, -0, assets/myapp/node_modules/resolve/test/precedence/aaa/main.js, -0, assets/myapp/node_modules/resolve/test/precedence/bbb/main.js, -0, assets/myapp/node_modules/resolve/test/resolver/cup.coffee, -0, assets/myapp/node_modules/resolve/test/resolver/foo.js, -0, assets/myapp/node_modules/resolve/test/resolver/baz/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/baz/quux.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_main/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/dot_slash_main/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/dot_slash_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/incorrect_main/package.json, -0, assets/myapp/node_modules/resolve/test/resolver/quux/foo/index.js, -0, assets/myapp/node_modules/resolve/test/resolver/same_names/foo.js, -0, assets/myapp/node_modules/resolve/test/resolver/same_names/foo/index.js, -0, assets/myapp/node_modules/socket.io-client/node_modules/debug/node.js, -0, assets/myapp/node_modules/socket.io-parser/node_modules/debug/node.js, -0, assets/myapp/node_modules/xmlhttprequest-ssl/tests/testdata.txt, -0, arsc, -I, C:\Users\backs\.androidjs\cache\1.apk, -S, C:\Users\backs\.androidjs\cache\androidjs-sdk\res, -M, C:\Users\backs\.androidjs\cache\androidjs-sdk\AndroidManifest.xml]
```

```
> androidjs -v  
2.1.8
```

**Comment by SY6Dave** [comment]
I also got this problem on androidjs version 2.1.8 and resolved it manually by downloading the latest .jar file for the Apktool (v2.4.1 tagged on their GitHub repo) and replacing the one inside node_modules/androidjs-builder/build_tools

**Comment by BlackEu** [comment]
I have a bug on **Windows** and **Ubuntu** when use `androidjs build`, I got error:

```cmd
copying assets ...
updating app name...
updating theme ...
Using SDK: 2.0.8
Building Apk ...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'C:\\Users\\█████\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\build_tools\\apktool.jar',
    'b',
    'C:\\Users\\█████\\.androidjs\\cache\\androidjs-sdk',
    '-o',
    'C:\\Users\\█████\\.androidjs\\cache\\█████.apk',
    '--frame-path',
    'C:\\Users\\█████\\.androidjs\\cache'
  ]
}
```
@Chhekur  @SY6Dave 
would you help me please ?

**Comment by BlackEu** [comment]
> I have a bug on **Windows** and **Ubuntu** when use `androidjs build`, I got error:
> 
> ```batchfile
> copying assets ...
> updating app name...
> updating theme ...
> Using SDK: 2.0.8
> Building Apk ...
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn java ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn java',
>   path: 'java',
>   spawnargs: [
>     '-jar',
>     'C:\\Users\\█████\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\build_tools\\apktool.jar',
>     'b',
>     'C:\\Users\\█████\\.androidjs\\cache\\androidjs-sdk',
>     '-o',
>     'C:\\Users\\█████\\.androidjs\\cache\\█████.apk',
>     '--frame-path',
>     'C:\\Users\\█████\\.androidjs\\cache'
>   ]
> }
> ```
> 
> @Chhekur @SY6Dave
> would you help me please ?

I'm referring to the attached answer, error gone after installing Java 1.8 and I'm able to build APK file now.
Thanks @Chhekur  , your project is better than Cordova ;) 

https://github.com/android-js/androidjs-builder/issues/29#issuecomment-561608581

**Comment by Chhekur** [comment]
Thanks for such words and I think you should look for docs actually because we have already mentioned about java >=1.8 as requirements

**Comment by BlackEu** [comment]
Thanks @Chhekur , I don't find it in documentation. even using the search form. 
And I hope you answer me about: Will androidjs support modules like "express", "ejs" soon ?

**Comment by Chhekur** [comment]
You can user express and ejs there is no issues in that
You can even use any npm package which is not hardware dependent

**Comment by BlackEu** [comment]
Thanks for reply @Chhekur ..

It works fine in browser but on start app I got error:
**Webpage not available** ([snapshot](https://i.imgur.com/IcGQ3Qo.jpg))


here is my **main.js** file content:
```js
const express = require('express');
const eApp = express();
const ejs = require('ejs');

eApp.set('view engine', 'ejs');
eApp.set('views', './views');
eApp.use( express.static('./') );

eApp.get('/', (req, res)=>{
    res.render('index');
});

eApp.get('/:pagename', (req, res)=>{
    res.render(req.params.pagename);
});

eApp.listen(3000); // even with a different port I got same issue
```
App directory structures
```
MyApp
    |__ css
    |__ js
    |__ images
    |__ views
    |     |__ index.ejs
    |     |__ ...etc.ejs
    |__ main.js
    |__ package.json
```
Could you give me a hint please ?

**Comment by Chhekur** [comment]
> Thanks for reply @Chhekur ..
> 
> It works fine in browser with no errors in nodejs consonle, but on start app on android device I got error:
> **Webpage not available** 
> ![snapshot](https://image.prntscr.com/image/h0JpsrqZQ7SqSpPT3hd3zA.png)
> 
> 
> here is my **main.js** file content:
> ```js
> const express = require('express');
> const eApp = express();
> const ejs = require('ejs');
> 
> eApp.set('view engine', 'ejs');
> eApp.set('views', './views');
> eApp.use( express.static('./') );
> 
> eApp.get('/', (req, res)=>{
>     res.render('index');
> });
> 
> eApp.get('/:pagename', (req, res)=>{
>     res.render(req.params.pagename);
> });
> 
> eApp.listen(3000); // even with a different port I got same issue
> ```
> App directory structure:
> ```
> MyApp
>     |__ css
>     |__ js
>     |__ images
>     |__ views
>     |     |__ index.ejs
>     |     |__ ...etc.ejs
>     |__ main.js
>     |__ package.json
> ```
> Could you give me a hint please ?
> 
> 
> 
> 

You are actually running server on port 3000 but by default app always look for index.html in views folder as entrypoint so what you do is create index.html in views folder with following javascript code, make sure you include androidjs in html file
```js
app.loadURL("http://localhost:3000"); 
```
Then it will redirect to your server route

**Comment by BlackEu** [comment]
Thanks for support @Chhekur .
this project is awesome! ♥
