### ISSUE TITLE
Error on updating android-sdks

### ISSUE THREAD

**Issue by Romans96** [android-js/androidjs-builder#31]
Hello! When i try to update the android sdks it return this error:

> $ androidjs u
> updating ... 
> ㋛ using androidjs-sdk {"version":"2.0.2"}
> C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\progress\lib\node-progress.js:55
>     if ('number' != typeof options.total) throw new Error('total required');
>                                           ^
> 
> Error: total required
>     at new ProgressBar (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\progress\lib\node-progress.js:55:49)
>     at Request.<anonymous> (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\test.js:179:23)
>     at Request.emit (events.js:189:13)
>     at reportState (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request-progress\index.js:83:21)
>     at call (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\throttleit\index.js:28:16)
>     at Object.throttled [as reportState] (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\throttleit\index.js:20:26)
>     at onData (C:\Users\Mattia\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request-progress\index.js:44:36)
>     at IncomingMessage.emit (events.js:194:15)
>     at addChunk (_stream_readable.js:284:12)
>     at readableAddChunk (_stream_readable.js:265:11)

**Comment by Chhekur** [comment]
run the same command repeatedly until it starts downloading the sdk ; )

**Comment by Romans96** [comment]
> run the same command repeatedly until it starts downloading the sdk ;

I'm continuing from half an hour, but the error is the same without any changes

**Comment by Chhekur** [comment]
we are actually implementing `androidjs-builder` from scratch so it'll solve most of the problems ; )

**Comment by yanickrochon** [comment]
.... this has to be the most duct-type answer I have seen in a long tme: "execute command until it runs". Clearly, some asynchronous process is being executed while the program considers it synchronous.

This is not a proper solution even though it works.

**Comment by Chhekur** [comment]
> .... this has to be the most duct-type answer I have seen in a long tme: "execute command until it runs". Clearly, some asynchronous process is being executed while the program considers it synchronous.
> 
> This is not a proper solution even though it works.

Yes, you are right this is not the proper solution that's why we are implementing it from scratch and will be available soon ; )

**Comment by Chhekur** [comment]
Hey, we have release new version of `androidjs-builder@2.1.4`, which may solve all the existing problem.
So you can upgrade to the latest version `2.1.4` and enjoy.

Follow these instruction to upgrade `androidjs-builder` to latest

```bash
$ npm uninstall -g androidjs-builder
$ npm install -g androidjs-builder@2.1.4
```

Feel free to ask in case of any problem ; )
