### ISSUE TITLE
Cannot build my app

### ISSUE THREAD

**Issue by posteal** [android-js/androidjs-builder#39]
Hello, I tried to build the app but it returns me this error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root@vmi433914:/home/simonefracassetti/sms-gateway-build/v1/data# 
```

Ubuntu 20.04 LTS

**Comment by lukew3** [comment]
I think you are missing the jdk. Try `sudo apt install default-jdk`.

**Comment by codmlifer** [comment]
> Я думаю, вам не хватает jdk. Попробуйте `sudo apt install default-jdk`.

I'm trying to install but I get this error:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/default-jdk - Not found
npm ERR! 404
npm ERR! 404  'default-jdk@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
