### ISSUE TITLE
Error when building (with -f argument and without it)

### ISSUE THREAD

**Issue by Danscath** [android-js/androidjs-builder#41]
Im getting the next error when trying to build in debug a androidjs app I will show u all commands, cause is not to much, im using the docs so I create a app, then try to build.

This first part when i open the shell and create the project, cheking node first
```Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Prueba la nueva tecnología PowerShell multiplataforma https://aka.ms/pscore6

PS C:\Users\Dani\proyectos> node -v
v14.15.1
PS C:\Users\Dani\proyectos\android> androidjs init
? Application name: app_template
? Project type: webview
   $cd app_template
   $npm install
   $npm run start:dev
   $npm run build
```
And not when im tying to build
```
PS C:\Users\Dani\proyectos\android> cd .\app_template\
PS C:\Users\Dani\proyectos\android\app_template> androidjs build -f
copying assets ...
updating app name...
Setting app version ...
Version Code: 1000032  
Version Name: 1.0.0    
updating theme ...
Using SDK: 2.2.0
Building Apk ...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'C:\\Users\\Dani\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\build_tools\\apktool.jar',
    'b',
    'C:\\Users\\Dani\\.androidjs\\cache\\androidjs-sdk',
    '-o',
    'C:\\Users\\Dani\\.androidjs\\cache\\app_template.apk',
    '--frame-path',
    'C:\\Users\\Dani\\.androidjs\\cache'
  ]
}```

Any idea?

**Comment by Danscath** [comment]
No jaba
